apiVersion: v1
kind: ConfigMap
metadata:
  name: age-calculator-config
  namespace: age-calculator
  labels:
    app.kubernetes.io/name: age-calculator
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: age-calculator-system
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
  JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"
