apiVersion: v1
kind: Service
metadata:
  name: age-calculator-service
  namespace: age-calculator
  labels:
    app.kubernetes.io/name: age-calculator
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: age-calculator-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: age-calculator
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
